### ISSUE TITLE
How to add new instructions?

### ISSUE THREAD

**Issue by DooyoungKim** [riscv-software-src/riscv-isa-sim#15]
![image](https://cloud.githubusercontent.com/assets/11660331/6848418/76e92834-d410-11e4-96ed-8de6fa3b84d3.png)
Is there any other detail explanation about add new instructions in RISC-V?
Can you explain it a bit more concretely for me, please?

**Comment by colinschmidt** [comment]
After determining what your new instruction does you would add a header file that implements the functionality in spike. Which would be something similar to any of the other header files in `riscv/insns/`

In order to generate the opcode matching logic/constants we use a separate repo (riscv-opcodes) to automate that process. Opening the opcodes file shows a list of current instructions and how they are encoded. You would need to add a line to this file something like 

```
myinst    rd rs1 rs2           14..12=2 6..2=0x0E 1..0=3
```

Conveniently the script that processes the opcodes file will tell you if your encoding overlaps with any of the existing opcodes, when you run it via `make install`

After this rebuilding spike should now recognize and be able to simulate your new instruction by the encoding you have given it.
