### ISSUE TITLE
Misaligned ld/st

### ISSUE THREAD

**Issue by ethanhz** [riscv-software-src/riscv-isa-sim#239]
Is there a reason why  #define for RISCV_ENABLE_MISALIGNED is not set as a default?
Based on the ISA spec, misaligned ld/st are legal. Shouldn't Spike support them as a default?

**Comment by aswaterman** [comment]
The ISA spec says that unprivileged code can use misaligned loads and stores, which is different than saying they are supported in hardware. Spike’s default matches the majority of hardware implementations we’re aware of, in that M-mode exception handlers emulate these instructions. So we think this is the most pragmatic default.

**Comment by ethanhz** [comment]
Shouldn't Spike, as a functional simulator, match anything that is defined
as valid behavior by ISA?

Choosing not to support misaligned is implementation specific.

**Comment by aswaterman** [comment]
Choosing to provide them is also implementation-specific. The only thing that matters is that unprivileged software is exposed the same interface.

In any event, there’s a configure flag that does what you want. For pragmatic reasons, we should not change the default, because it will cause problems for existing users.

**Comment by aswaterman** [comment]
BTW, if we were to start from scratch, I’d support your position. Changing the default option is more trouble than it’s worth, though.

**Comment by ethanhz** [comment]
Thanks for clarifying.
