### ISSUE TITLE
Disallowing LR.w and SC.w accesses to I/O Space

### ISSUE THREAD

**Issue by ben-marshall** [riscv-software-src/riscv-isa-sim#272]
I see that #217 introduced a constraint on `LR.w`/`SC.w` execution, where they will raise an exception if they try to access memory mapped I/O.

The constraint is implemented here: https://github.com/riscv/riscv-isa-sim/blob/master/riscv/mmu.h#L194

I can't find a corresponding passage in the ISA specification which requires this behavior. Is this a Spike specific behavior or a modelling of a particular existing system like Rocket?

It seems a strange constraint to me, given that predictable access to peripherals is a good use case for `LR`/`SC`, but I can understand that some systems might only implement reservations in "normal" memory as well.

**Comment by aswaterman** [comment]
The physical-memory attributes section in the privileged architecture mentions that it's a property of a given memory region as to whether LR, SC, etc. are supported.  So there's nothing wrong with disallowing LR/SC on I/O space.

It is indeed the case that disallowing LR/SC matches the RISC-V hardware implementations that I'm aware of.  (Many buses don't support LR/SC.)

I wouldn't have a problem with making another configure-time switch to allow this, but it wouldn't be especially useful as-is, because none of the simulated devices hooked up to Spike would benefit from it.
