### ISSUE TITLE
Can HS-mode take vssip/vseip/vstip interrupt?

### ISSUE THREAD

**Issue by tianhu-zeng** [riscv-software-src/riscv-isa-sim#612]
My understanding is that vs interrupt trap to the specific mode which based  on mideleg and hideleg about vseip/vstip/vssip.
All vs interrupts were traped to VS mode on Spike. Are there special considerations for this implementation? Thanks!
![vs-int-delegate](https://user-images.githubusercontent.com/59038826/101155888-bff2fe00-3662-11eb-9f81-dbeb8dbb0d7a.png)

@avpatel

**Comment by avpatel** [comment]
The bits corresponding to VS interrupts are hardwired to 1 in MIDELEG CSR so M-mode can never take VS interrupt. This is in accordance with section "5.4.2 Machine Interrupt Delegation Register (mideleg)".

The H-extension spec certainly allows HS-mode to take VS interrupts because VS interrupt bits are writeable in HIDELEG CSR. I think "~MIP_VS_MASK" in take_interrupt() should be replaced with "~state.hideleg". Let me send a fix for this.

**Comment by avpatel** [comment]
I have add fix to the following PR (https://github.com/riscv/riscv-isa-sim/pull/618)
