### ISSUE TITLE
Simulator fails with 'trap_store_access_fault' with any test

### ISSUE THREAD

**Issue by ghost** [riscv-software-src/riscv-isa-sim#74]
Any test or benchmark fails at start with error `trap_store_access_fault`.
any-bit pk.
Why spike can deny storing io?
Latest pull at the time of issue (db6051f2001243e5132f224ece06753aff85748d)

**Comment by evancox10** [comment]
This happens if you try to load the ELF file to somewhere other than RAM. elf loading goes through HTIF and writes to the sim's bus device. There must be a writable device at this location on the bus.

...At least that's the behavior a now, a year and a day after you posted this. I thought I'd post the explanation so other people could find the reason why this happens.

Make sure that the elf _entry symbol has a corresponding RAM in spike, and that it's big enough to hold the code and other data you're loading.

**Comment by ghost** [comment]
@evancox10 I still have this as my project, it's just conservated for now.
I'm sure I can use that info later, thank you

**Comment by ghost** [comment]
Sorry, currently I left working with this project and cannot force this issue anymore.
