### ISSUE TITLE
Can not run v isa extension in user space

### ISSUE THREAD

**Issue by vigoss30611** [riscv-software-src/riscv-isa-sim#773]
#771 
It seems that somewhere have disable the v isa extension. But I find In riscv-pk, mstatus[10:9] have set 0x3 in function (mstatus_init),and I can run v isa extension(in
linux-5.13, like that:
asm volatile("vsetvli a4, a0, e32, m8, ta, ma");
even if I add this before run_init_process() (in init/main.c).
```
if (ramdisk_execute_command) {
  ret = run_init_process(ramdisk_execute_command);
  asm volatile("vsetvli a4, a0, e32, m8, ta, ma");
  if (!ret)
    return 0;
  pr_err("Failed to execute %s (error %d)\n",
         ramdisk_execute_command, ret);
}
```
But I cannot run it in user space, like #771 . Maybe somewhere in Linux kernel change the value of mstatus, or disabled v isa extension. but I cannot find out it...
Can someone help me!

**Comment by aswaterman** [comment]
This repo's issue tracker isn't the best place to ask this question, since it doesn't appear to be a problem with Spike.  You might need to ask on a Linux mailing list or something.

If you are running a version of the kernel that does not know about the V extension, then the kernel is probably zeroing `sstatus.VS`, because a kernel that doesn't know about the V extension doesn't know about `sstatus.VS`.

Beyond that, we can't really help from here.

**Comment by scottj97** [comment]
Closing as not a Spike issue.
